# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
../spec/vendor/apds/4.1/apds-api-4.1.yaml:
  operation-4xx-response:
    - '#/paths/~1places/get/responses'
    - '#/paths/~1observations/get/responses'
    - '#/paths/~1contacts/get/responses'
    - '#/paths/~1rights~1specs/get/responses'
    - '#/paths/~1rates/get/responses'
    - '#/paths/~1rates/post/responses'
    - '#/paths/~1sessions/get/responses'
    - '#/paths/~1rights~1assigned/get/responses'
    - '#/paths/~1quotes/get/responses'
    - '#/paths/~1quotes/post/responses'
  struct:
    - '#/components/schemas/ReferenceToQuote/x-tags'
    - '#/components/schemas/ReferenceQuoteExtension/x-tags'
    - '#/components/schemas/ReferenceQuoteNew/x-tags'
    - '#/components/schemas/QuoteRightRequest/x-tags'
    - '#/components/schemas/ReferencedRightSpecification/x-tags'
    - '#/components/schemas/QuoteRightResponse/x-tags'
    - '#/components/schemas/ResponseReasonEnum/x-tags'
    - '#/components/schemas/Option/x-tags'
    - '#/components/schemas/QuoteExpiration/x-tags'
    - '#/components/schemas/Identifiers/x-tags'
    - '#/components/schemas/FinancialQuote/x-tags'
    - '#/components/schemas/QuoteSessionExtensionRequest/x-tags'
    - '#/components/schemas/QuoteSessionExtensionResponse/x-tags'
    - '#/components/schemas/QuoteRightResponseExtensionReasonEnum/x-tags'
  security-defined:
    - '#/paths/~1places/get/security/0/oAuth'
    - '#/paths/~1places/post/security/0/oAuth'
    - '#/paths/~1places~1{id}/get/security/0/oAuth'
    - '#/paths/~1places~1{id}/put/security/0/oAuth'
    - '#/paths/~1places~1{id}/delete/security/0/oAuth'
    - '#/paths/~1contacts/get/security/0/oAuth'
    - '#/paths/~1contacts~1{contactId}/get/security/0/oAuth'
    - '#/paths/~1rights~1specs/get/security/0/oAuth'
    - '#/paths/~1rights~1specs/post/security/0/oAuth'
    - '#/paths/~1rights~1specs~1{id}/get/security/0/oAuth'
    - '#/paths/~1rights~1specs~1{id}/put/security/0/oAuth'
    - '#/paths/~1rights~1specs~1{id}/delete/security/0/oAuth'
    - '#/paths/~1rates/get/security/0/oAuth'
    - '#/paths/~1rates/post/security/0/oAuth'
    - '#/paths/~1rates~1{id}/get/security/0/oAuth'
    - '#/paths/~1rates~1{id}/put/security/0/oAuth'
    - '#/paths/~1rates~1{id}/delete/security/0/oAuth'
    - '#/paths/~1sessions/get/security/0/oAuth'
    - '#/paths/~1sessions/post/security/0/oAuth'
    - '#/paths/~1sessions~1{id}/get/security/0/oAuth'
    - '#/paths/~1sessions~1{id}/put/security/0/oAuth'
    - '#/paths/~1sessions~1{id}/delete/security/0/oAuth'
    - '#/paths/~1rights~1assigned/get/security/0/oAuth'
    - '#/paths/~1rights~1assigned/post/security/0/oAuth'
    - '#/paths/~1rights~1assigned~1{id}/get/security/0/oAuth'
    - '#/paths/~1rights~1assigned~1{id}/put/security/0/oAuth'
    - '#/paths/~1rights~1assigned~1{id}/delete/security/0/oAuth'
../spec/openapi/apx.yaml:
  operation-4xx-response:
    - '#/paths/~1.well-known~1apx-configuration/get/responses'
