#!/usr/bin/env node
/**
 * Writes spec/edition.json — the manifest that pins exactly what one APX
 * edition comprises (Part 3 §3.2, §3.4).
 *
 * Why this exists: "adopt APX" is not a reviewable proposition unless the
 * proposal names the artifacts. This file answers, for one edition: which
 * bundle (by SHA-256, not by branch), which registry versions, which APDS
 * release and its checksum, which Parts, and which conformance classes.
 *
 * Generated, never hand-edited, so it cannot drift from what CI validated.
 * Runs at the end of `npm run spec:bundle`; CI then checks it is unchanged,
 * which fails the build if someone edits a registry and forgets to rebuild.
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const REG_DIR = join(ROOT, 'spec', 'registries');
const DIST = join(ROOT, 'spec', 'dist');
const STANDARD = join(ROOT, 'docs', 'standard');
const OVERLAY_DIR = join(ROOT, 'spec', 'openapi', 'overlays');
const OUT = join(ROOT, 'spec', 'edition.json');

const sha256 = (path) => createHash('sha256').update(readFileSync(path)).digest('hex');

const { version, license } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const bundle = JSON.parse(readFileSync(join(DIST, 'apx-v1.json'), 'utf8'));

const registries = {};
for (const file of readdirSync(REG_DIR).filter((f) => f.startsWith('apx-') && f.endsWith('.json')).sort()) {
  const doc = JSON.parse(readFileSync(join(REG_DIR, file), 'utf8'));
  registries[doc.name ?? file] = {
    version: doc.version,
    entries: doc.userDefinedCodeListEntries?.length ?? 0,
    locator: doc.locator,
    sha256: sha256(join(REG_DIR, file)),
  };
}

const parts = readdirSync(STANDARD)
  .filter((f) => f.endsWith('.md'))
  .sort()
  .map((file) => {
    const heading = readFileSync(join(STANDARD, file), 'utf8')
      .split('\n')
      .find((line) => line.startsWith('# '));
    return { file, title: heading ? heading.replace(/^#\s*/, '') : file };
  });

const overlays = readdirSync(OVERLAY_DIR)
  .filter((f) => f.endsWith('.yaml'))
  .sort()
  .reduce((acc, f) => {
    acc[`spec/openapi/overlays/${f}`] = sha256(join(OVERLAY_DIR, f));
    return acc;
  }, {});

// The vendored APDS release and the checksum that guards it byte-identical.
const vendorChecksum = readFileSync(
  join(ROOT, 'spec', 'vendor', 'apds', '4.1', 'CHECKSUM.sha256'),
  'utf8'
).trim();

const edition = {
  $comment: 'GENERATED by tools/build-edition.mjs — do not edit. Regenerate with `npm run spec:bundle`.',
  edition: version,
  status: 'draft',
  license,
  apiVersion: bundle.info.version,
  extension: bundle.info['x-apds-extension'] ?? null,
  apds: {
    release: '4.1',
    checksum: vendorChecksum,
    source: 'https://github.com/parkingdata/spec',
  },
  normativeArtifacts: {
    bundle: {
      'spec/dist/apx-v1.yaml': sha256(join(DIST, 'apx-v1.yaml')),
      'spec/dist/apx-v1.json': sha256(join(DIST, 'apx-v1.json')),
    },
    overlays,
    registries,
    writtenStandard: parts,
  },
  surface: {
    paths: Object.keys(bundle.paths ?? {}).length,
    schemas: Object.keys(bundle.components?.schemas ?? {}).length,
    conformanceClasses: (
      JSON.parse(readFileSync(join(REG_DIR, 'apx-conformance-classes.json'), 'utf8'))
        .userDefinedCodeListEntries ?? []
    ).map((e) => e.definedValue),
  },
};

writeFileSync(OUT, JSON.stringify(edition, null, 2) + '\n');
console.log(
  `[spec:edition] edition ${edition.edition}: ${Object.keys(registries).length} registries, ` +
    `${parts.length} parts, ${edition.surface.paths} paths, ${edition.surface.schemas} schemas`
);
